server:
  port: 8080

spring:
  application:
    name: app
  datasource:
    password: pd
    url: jdbc:postgresql://localhost:5432/core
    username: pd
  security:
    user:
      name: user
      password: user
    filter:
      order: -200
  jpa:
    open-in-view: false
springdoc:
  show-actuator: false
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

project-d:
  jwt:
    key: "9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9"
    access-token-expiration: 2628000000
    refresh-token-expiration: 4628000000
  cors:
    allowed-urls: [ 'http://localhost:5173' ]
    allowed-methods: [ 'POST', 'GET', 'PUT', 'DELETE', 'PATCH' ]
  integrations:
    rule-book:
      api-url: api
      base-url: http://localhost:8081
      rooms-url: rooms
      races-url: races
      classes-url: classes
      abilities-url: abilities
      skills-url: skills
      skills-by-code-url: byCode
      skills-by-class-url: byClass
    character-sheet:
      api-url: api
      base-url: http://localhost:8082
      rooms-url: rooms
      characters-url: characters
      header-url: header
      subheader-url: subheader
      abilities-url: abilities
      bonus-url: bonus
      health-url: health
      update-current-health-url: updateCurrent
      skills-url: skills
      update-mastery-url: updateMastery
