spring:
  application:
    name: app
  datasource:
    password: pd
    url: jdbc:postgresql://localhost:5432/core
    username: pd
  security:
    user:
      name: user
      password: user
    filter:
      order: -200

project-d:
  jwt:
    key: "9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9"
    access-token-expiration: 3600000
    refresh-token-expiration: 86400000
