server:
  port: 8080

spring:
  application:
    name: app
  datasource:
    password: pd
    url: jdbc:postgresql://localhost:5432/core
    username: pd
  security:
    user:
      name: user
      password: user
    filter:
      order: -200
  jpa:
    open-in-view: false
springdoc:
  show-actuator: false
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

project-d:
  jwt:
    key: "9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9"
    access-token-expiration: 2628000000
    refresh-token-expiration: 4628000000
  cors:
    allowed-urls: [ 'http://localhost:5173' ]
    allowed-methods: [ 'POST', 'GET', 'PUT', 'DELETE', 'PATCH' ]
  integrations:
    rule-book:
      base-url: http://localhost:8081
      rooms-url: /api/rooms
      races-url: /api/races
      classes-url: /api/classes
      abilities-url: /api/abilities
      skills-url: /api/skills
      skills-by-code-url: /api/skills/byCode
      skills-by-class-url: /api/skills/byClass
